sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sergeyn0vik/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sergeyn0vik/react-test npm test

after_success:
  - docker build -t sergeyn0vik/multi-client ./client
  - docker build -t sergeyn0vik/multi-nginx ./nginx
  - docker build -t sergeyn0vik/multi-server ./server
  - docker build -t sergeyn0vik/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sergeyn0vik/multi-client
  - docker push sergeyn0vik/multi-nginx
  - docker push sergeyn0vik/multi-server
  - docker push sergeyn0vik/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-central-1-883095210921
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY